fix-call-me
so2niko/Dp-193_proj1 pull request #109
Opened 2020-10-26 22:27 UTC by MarinaPasternak

2020-10-26 22:51 UTC, PavelKundenko requested changes

2020-10-26 22:51 UTC, PavelKundenko commented on app/components/callMe/call-controller.js
> +    this.model.sendData(phoneNumber);
Add window closing on submit
(Create such method in view and use this method)

2020-10-27 08:25 UTC, MarinaPasternak commented on app/components/callMe/call-controller.js
> +    this.model.sendData(phoneNumber);
Done, check please it in the View

2020-10-27 08:28 UTC, MozdolevskyiMaksym approved these changes

2020-10-27 08:38 UTC, Icemandov approved these changes

2020-10-27 09:00 UTC, PavelKundenko commented on app/components/callMe/call-view.js
> +      form.classlist.add(“form-hide”);
Such strange quotes.. Does it work?

2020-10-27 09:07 UTC, MarinaPasternak commented on app/components/callMe/call-view.js
> +      form.classlist.add(“form-hide”);
Max said  that I should write like that

2020-10-27 09:15 UTC, archontis-cpu approved these changes

2020-10-27 09:15 UTC, PavelKundenko approved these changes

2020-10-27 10:30 UTC, merged