Initial MVC carcass
so2niko/Dp-193_proj1 pull request #13
Opened 2020-10-08 17:09 UTC by PavelKundenko

- Example MVC component added
- Publisher added
- Observer added

2020-10-08 17:23 UTC, archontis-cpu approved these changes

2020-10-09 09:34 UTC, so2niko requested changes

2020-10-09 09:34 UTC, so2niko commented on app/components/Template/template-controller.js
> +import { TemplateModel } from './template-model.js';
rename folder "Template" to lower case.
We will use lowercase style for folder/file naming

2020-10-09 09:34 UTC, so2niko commented on app/helpers/observer.js
> +export class Observer {
delete observer. We will use publisher))

2020-10-09 09:34 UTC, so2niko commented on app/helpers/publisher.js
> +    !this.subscribers[event] ? this.subscribers[event] = [] : this.subscribers[event];
`else null`

2020-10-09 09:34 UTC, so2niko commented on app/helpers/publisher.js
> +    !this.subscribers[event] ? this.subscribers[event] = [] : this.subscribers[event];
`else null`

2020-10-09 09:34 UTC, so2niko commented on app/helpers/publisher.js
> +    !this.subscribers[event] ? this.subscribers[event] = [] : this.subscribers[event];
`else null`

2020-10-09 10:23 UTC, so2niko approved these changes
ок

2020-10-09 10:27 UTC, MozdolevskyiMaksym approved these changes

2020-10-09 11:24 UTC, merged