Kundenko 23 mvc component filter
so2niko/Dp-193_proj1 pull request #57
Opened 2020-10-15 10:30 UTC by PavelKundenko

### Added filter component 

![image](https://user-images.githubusercontent.com/47292994/96111727-418fa080-0eea-11eb-96c3-02591cb11cf1.png)

![image](https://user-images.githubusercontent.com/47292994/96111757-4f452600-0eea-11eb-87a0-f29b30033afd.png)

![image](https://user-images.githubusercontent.com/47292994/96111770-579d6100-0eea-11eb-9481-03d67d2b673a.png)

2020-10-15 18:18 UTC, Anastasiia0999 approved these changes

2020-10-15 19:59 UTC, so2niko requested changes

2020-10-15 19:59 UTC, so2niko commented on app/components/filter/filter-controller.js
> +import { FilterView } from './filter-view.js';
Does we use spaces with {}?

If it's true, add this check to ES Lint, please. 
I've already seen code like this, but without spaces in Anastasia's PR.

2020-10-15 19:59 UTC, so2niko commented on app/components/filter/filter-model.js
> +    if (formElement.type !== 'submit') {
Rewrite **3** if conditions. It is too much

2020-10-15 19:59 UTC, so2niko commented on app/components/filter/filter-view.js
> +    this.rootNode.insertAdjacentHTML('afterbegin', `
Cut this method to 2 methods

2020-10-15 19:59 UTC, so2niko commented on app/components/filter/filter-view.js
> +      return `
Too much returns in method. Rewrite with 1 return

2020-10-15 19:59 UTC, so2niko commented on app/components/filter/filter-view.js
> +    this.filterForm.parentNode.style.display = 'flex';
Find it's parent in constructor or other method and link exact to it.

Do not use here parentNode

2020-10-15 19:59 UTC, so2niko commented on app/components/filter/filter-view.js
> +    this.filterForm.parentNode.style.display = 'none';
Second link to this element. Add property to view with link to this element

2020-10-16 12:38 UTC, so2niko requested changes

2020-10-16 12:38 UTC, so2niko commented on app/components/filter/filter-model.js
> +  extractFormData = (event) => [...event.target.querySelectorAll('input')].reduce((selectedProperties, formElement) => {
move this code to view

2020-10-16 12:38 UTC, so2niko commented on app/components/filter/filter-model.js
> +  filterData = (carsData, filterParams) => carsData
too hard code.
6 if conditions and many `return false` construction.
Remaster this code

2020-10-17 09:40 UTC, so2niko commented on app/components/filter/filter-model.js
> +    if (formElement.type !== 'submit') {
still there

2020-10-17 09:52 UTC, so2niko requested changes

2020-10-17 09:52 UTC, so2niko commented on app/components/filter/filter-model.js
> +    if (formElement.type !== 'submit') {
still there

2020-10-17 09:52 UTC, so2niko commented on app/components/filter/filter-view.js
> +    this.rootNode.insertAdjacentHTML('afterbegin', `
1 method - render
2 method - find elements and add event listeners to them

2020-10-17 09:52 UTC, so2niko commented on app/components/filter/filter-view.js
> +    this.filterForm.parentNode.style.display = 'flex';
I don`t see changes

2020-10-17 09:52 UTC, so2niko commented on app/components/filter/filter-view.js
> +    this.filterForm.parentNode.style.display = 'none';
I don`t see changes

2020-10-17 14:44 UTC, PavelKundenko commented on app/components/filter/filter-model.js
> +    if (formElement.type !== 'submit') {
It was fixed yesterday. Check latest commits, please.
![image](https://user-images.githubusercontent.com/47292994/96339909-29618200-10a0-11eb-9fbe-9f349a721055.png)

2020-10-17 14:47 UTC, PavelKundenko commented on app/components/filter/filter-view.js
> +    this.filterForm.parentNode.style.display = 'flex';
It was fixed yesterday, check latest commits, please

2020-10-17 14:48 UTC, PavelKundenko commented on app/components/filter/filter-view.js
> +    this.filterForm.parentNode.style.display = 'none';
Same as previous

2020-10-17 14:51 UTC, PavelKundenko commented on app/components/filter/filter-model.js
> +  filterData = (carsData, filterParams) => carsData
Check new version, please:
- added flag to avoid early returns
- conditions structure became flat

2020-10-17 18:31 UTC, so2niko approved these changes

2020-10-18 10:40 UTC, MozdolevskyiMaksym approved these changes

2020-10-18 14:42 UTC, merged