MVC Component: Header
so2niko/Dp-193_proj1 pull request #58
Opened 2020-10-15 10:49 UTC by Anastasiia0999

![image](https://user-images.githubusercontent.com/55295369/96113586-0c388200-0eed-11eb-97f5-c2bf90d72514.png)

2020-10-15 11:00 UTC, PavelKundenko commented on app/components/header/header-view.js
> +      this.home = home;
I think that it's better to name these handles in a more explicit way, for example `this.handleContactsClick`

2020-10-15 18:03 UTC, PavelKundenko approved these changes

2020-10-15 18:08 UTC, Winchestery approved these changes

2020-10-15 18:14 UTC, MarinaPasternak approved these changes

2020-10-15 19:37 UTC, so2niko requested changes
Check, please,  situation with svg file

2020-10-15 19:37 UTC, so2niko commented on app/components/header/header-view.js
> +                            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-search" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
Save svg in file and connect here in img or something else

2020-10-15 19:52 UTC, MozdolevskyiMaksym approved these changes

2020-10-16 08:05 UTC, Anastasiia0999 commented on app/components/header/header-view.js
> +                            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-search" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
done

2020-10-16 12:51 UTC, so2niko approved these changes

2020-10-16 13:55 UTC, merged