MVC Component: Main Gallery
so2niko/Dp-193_proj1 pull request #61
Opened 2020-10-15 21:51 UTC by MozdolevskyiMaksym

![MainGallery1](https://user-images.githubusercontent.com/72501713/96189265-d7f2af00-0f48-11eb-8334-453fe9d723c1.jpg)
![MainGallery2](https://user-images.githubusercontent.com/72501713/96189600-71ba5c00-0f49-11eb-9fd4-901a9ed9d994.jpg)
![MainGallery3](https://user-images.githubusercontent.com/72501713/96189603-73841f80-0f49-11eb-9c96-7ee79173ab48.jpg)

2020-10-16 07:18 UTC, iklopov approved these changes

2020-10-16 07:42 UTC, MarinaPasternak approved these changes

2020-10-16 08:13 UTC, Anastasiia0999 commented
Do we use export default? 
```
export default class ViewCarsGallery 
export default class ControllerCarsGallery
export default class ModelCarsGallery
```

2020-10-16 08:18 UTC, Anastasiia0999 commented
It`s better to split into two functions: renderGallery and renderCar
![image](https://user-images.githubusercontent.com/55295369/96233802-3ea3b700-0fa1-11eb-8021-b73354c14156.png)

2020-10-16 08:27 UTC, Anastasiia0999 commented
`this.view = new ViewCarsGallery(this.handleFilterButton, this.handleShowAll, this.handleCarDetails, this.handleLoadMore);`
There are 4 callbacks here. Try to use one func instead.
getMethods = () => ({
    handleFilterButton: this.handleFilterButton,
    ...
  });

2020-10-16 10:11 UTC, PavelKundenko approved these changes

2020-10-16 10:11 UTC, PavelKundenko commented on app/components/cars-gallery/controller-cars-gallery.js
> +  handleLoadMore = _ => {
Just a small comment: I think it's better use "( )" than pseudo-argument "_"

2020-10-16 10:30 UTC, Anastasiia0999 commented
Yoy render info for one car only => renderCar not  renderCars
`renderCars = ({photoUrl, brand, model, price, id}) => {`

2020-10-16 13:08 UTC, so2niko requested changes

2020-10-16 13:08 UTC, so2niko commented on app/components/cars-gallery/controller-cars-gallery.js
> +    this.model.filteredCars.length = 0;
This code must be named and moved to some method in model, like `clearFilteredData `or else

2020-10-16 13:08 UTC, so2niko commented on app/components/cars-gallery/controller-cars-gallery.js
> +    this.model.filteredCars.length = 0;
This code must be named and moved to some method in model, like clearFilteredData or else

2020-10-16 13:08 UTC, so2niko commented on app/components/cars-gallery/model-cars-gallery.js
> +    fetch('../../../base/database.json')
move link to class property

2020-10-16 14:53 UTC, Anastasiia0999 approved these changes

2020-10-16 15:25 UTC, MozdolevskyiMaksym commented on app/components/cars-gallery/controller-cars-gallery.js
> +    this.model.filteredCars.length = 0;
I`v already changed it, you can check

2020-10-16 15:27 UTC, MozdolevskyiMaksym commented on app/components/cars-gallery/controller-cars-gallery.js
> +    this.model.filteredCars.length = 0;
It`s also done

2020-10-16 15:28 UTC, MozdolevskyiMaksym commented on app/components/cars-gallery/model-cars-gallery.js
> +    fetch('../../../base/database.json')
You can also check it)

2020-10-17 09:37 UTC, so2niko requested changes

2020-10-17 09:37 UTC, so2niko commented on app/components/cars-gallery/controller-cars-gallery.js
> +    this.model.filteredCars.length = 0;
same code...
![image](https://user-images.githubusercontent.com/9075641/96333810-a4ad3e80-1074-11eb-8cd9-2010f6ec37b5.png)
Move to model, not controller

2020-10-17 09:37 UTC, so2niko commented on app/components/cars-gallery/view-cars-gallery.js
> +  }
Why in some methods u use `;` at the end of line, but do not use here?

2020-10-19 07:34 UTC, so2niko requested changes

2020-10-19 07:34 UTC, so2niko commented on app/components/cars-gallery/view-cars-gallery.js
> +  };
why `; `is here?

2020-10-19 07:34 UTC, so2niko commented on app/components/cars-gallery/view-cars-gallery.js
> +  };
why `; `is here?

2020-10-19 07:34 UTC, so2niko commented on app/components/cars-gallery/view-cars-gallery.js
> +  };
why `; `is here?

2020-10-19 07:34 UTC, so2niko commented on app/components/cars-gallery/view-cars-gallery.js
> +  };
why `; `is here?

2020-10-20 11:30 UTC, so2niko approved these changes

2020-10-20 11:31 UTC, merged