Winchestery - Contact/Partners Components
so2niko/Dp-193_proj1 pull request #65
Opened 2020-10-16 17:43 UTC by Winchestery

Added:
1.MVC Contacts component
2.MVC Partners component
Fixed:
1.Footer attactment fixed
Changed
1. CSS structure changed(_styles.css deleted, because of import <file>, which was done incorrectly in my previous commit)
2. The inner of _styles.scss was moved to main.scss( as far as we all have our own styles that belong to our our components)

2020-10-17 09:25 UTC, so2niko requested changes

2020-10-17 09:25 UTC, so2niko commented on app/components/partners/partners-view.js
> +        <section>
165 Lines of html code.
Can it be shorter with loop and arrays of urls?

2020-10-17 09:25 UTC, so2niko commented on app/helpers/publisher.js
> +export class Publisher {
**It must be default export.** 
Did I miss some changes?

2020-10-17 09:25 UTC, so2niko commented on app/main.js
> +
why new line here?

2020-10-17 15:29 UTC, PavelKundenko commented on app/components/contacts/contacts-controller.js
> +    showCallBack: this.handleCallBack,
I think that getMethods is redundant here, you can transer `this.handleCallBack` directly to view arguments

2020-10-19 21:46 UTC, PavelKundenko approved these changes

2020-10-19 21:46 UTC, PavelKundenko commented on app/components/template/template-model.js
> +export class TemplateModel {
Remove template component, we don't need it

2020-10-20 06:24 UTC, archontis-cpu approved these changes

2020-10-20 06:27 UTC, MozdolevskyiMaksym approved these changes

2020-10-20 11:20 UTC, Winchestery commented on app/components/contacts/contacts-controller.js
> +    showCallBack: this.handleCallBack,
it would be more clearly for me to leave it here for beter understanding and possible included changes after.

2020-10-20 11:20 UTC, Winchestery commented on app/components/partners/partners-view.js
> +        <section>
there are not so many lines in the last commit.
should i add a loop anyway?

2020-10-20 11:22 UTC, Winchestery commented on app/helpers/publisher.js
> +export class Publisher {
ok it is done

2020-10-20 11:23 UTC, Winchestery commented on app/main.js
> +
ok it is done

2020-10-20 11:58 UTC, so2niko approved these changes

2020-10-20 12:34 UTC, merged