Drozdov 55 slider
so2niko/Dp-193_proj1 pull request #77
Opened 2020-10-19 20:10 UTC by Icemandov

Added MVC Slider component

2020-10-19 20:24 UTC, Icemandov commented
Added Slider Loyout
![Slider_layout](https://user-images.githubusercontent.com/50587976/96507665-27dfb780-1262-11eb-9024-6020f8e309ca.PNG)

2020-10-19 21:15 UTC, PavelKundenko requested changes

2020-10-19 21:15 UTC, PavelKundenko commented on app/components/slider/slider-view.js
> +      <img src='${photoUrl[0]}' class='image opacity-0' id='sliderImg_${id}'>
Try to use data attribute instead of id. For example: `data-id="${id}"`

2020-10-19 21:15 UTC, PavelKundenko commented on app/components/slider/slider-view.js
> +    const imageBlock = document.querySelector(`#sliderImg_${id}`);
If you use data-attribute, selector will be like that: ``querySelector(`.image[data-id='${id}']`);``

2020-10-19 21:15 UTC, PavelKundenko commented on app/components/slider/slider-controller.js
> +
If you use data attributes, here will be something like that: 
`const car id = Number(event.target.dataset.id);`
`const data = //some code to get data for proper car`
`//notifier to open the car details window`

2020-10-19 21:15 UTC, PavelKundenko commented on app/components/slider/slider-model.js
> +  randomizer() {
If I am correct, `randomCar` property is used only once. I think that it's better to remove this property and make this function getter and use it when you need a random number.
f.e. `getRandomCar = () => Math.floor(Math.random() * this.data.length);`

2020-10-19 21:15 UTC, PavelKundenko commented on app/components/slider/slider-controller.js
> +      this.handleAutoPlay();
No need to use arrow callback, you can just write `setInterval(this.handleAutoPlay, this.model.slideInterval * 1000);`

2020-10-20 12:15 UTC, so2niko commented
This PR
close #70 
close #55

2020-10-20 13:09 UTC, PavelKundenko commented on app/components/slider/slider-controller.js
> +    console.log(car);
Remove redundant logs and comment

2020-10-20 13:09 UTC, PavelKundenko commented on app/main.js
> +fetch('http://localhost:8080/base/database.json').then((response) => response.json()).then((data) => publisher.notify('LOAD_DATA', data));
Remove this test code

2020-10-20 13:09 UTC, PavelKundenko commented on app/components/slider/slider-model.js
> +  getCarId(id) {
Better name this function `getCarById` or `getCarData`

2020-10-20 13:09 UTC, PavelKundenko commented on app/components/slider/slider-model.js
> +  randomCarsFilter() {
Maybe it's better to make this function getter and use it in controller

2020-10-20 15:05 UTC, PavelKundenko commented on app/components/slider/slider-controller.js
> +    this.handleLoadSliderWrapper();
I think that you can remove this method and put this code directly in `handleLoadData`
```
 this.view.renderWrapper();
 this.handleLoadSliderImages();
```

2020-10-20 17:14 UTC, so2niko approved these changes

2020-10-20 18:29 UTC, PavelKundenko approved these changes

2020-10-20 18:33 UTC, Anastasiia0999 approved these changes

2020-10-20 18:36 UTC, MozdolevskyiMaksym approved these changes

2020-10-20 18:55 UTC, merged