Helper 69
so2niko/Dp-193_proj1 pull request #91
Opened 2020-10-21 09:38 UTC by iklopov

mvc car details

2020-10-21 10:01 UTC, PavelKundenko requested changes

2020-10-21 10:01 UTC, PavelKundenko commented on app/components/car-details/view-car-details.js
> +    const container = document.querySelector('.car-container')
Better create class properties for popUp and container, because you use them in 2 methods (or even more than 2)

2020-10-21 10:01 UTC, PavelKundenko commented on app/components/car-details/view-car-details.js
> +  //main = document.querySelector('.main');
Remove redundant comments

2020-10-21 10:01 UTC, PavelKundenko commented on app/components/car-details/controller-car-details.js
> +  showCar = car => {
Use parentheses, please `showCar = (car) => {`

2020-10-21 10:01 UTC, PavelKundenko commented on app/components/car-details/view-car-details.js
> +    const popUp = document.querySelector('.container')
Do you really need this constant here?

2020-10-21 10:01 UTC, PavelKundenko commented on app/components/car-details/view-car-details.js
> +  getMethod = () => {
Better name this method "setListeners" or "addListeners"

2020-10-21 10:39 UTC, Icemandov commented on app/components/car-details/view-car-details.js
> +            </div>
Used the same URL twice

2020-10-21 11:19 UTC, PavelKundenko requested changes

2020-10-21 11:19 UTC, PavelKundenko commented on app/components/car-details/controller-car-details.js
> +import { ViewDetails } from "./view-car-details.js";
Use single quotes, please

2020-10-21 11:38 UTC, so2niko requested changes

2020-10-21 11:38 UTC, so2niko commented on app/components/car-details/model-car-details.js
> +
ADD METHOD
```
setCar(car){
  //copy object by value
}
```

2020-10-21 11:38 UTC, so2niko commented on app/components/car-details/controller-car-details.js
> +    this.model.car = car;
use method `setCar`

2020-10-21 11:38 UTC, so2niko commented on app/components/car-details/view-car-details.js
> +  renderCarCard({ id, photoUrl, brand, model, price, color, country, year, seats, 'body-type': bodyType, transmission,'engine-capacity': engineCapacity,
add line in code with it

2020-10-21 11:38 UTC, so2niko commented on app/components/car-details/view-car-details.js
> +    const closePopup = document.querySelector('.close-popUp');
```
.color-container
.makeOrder
.close-popUp
```

to one naming style

2020-10-21 11:38 UTC, so2niko commented on app/components/car-details/view-car-details.js
> +    const colorContainer = document.querySelector('.color-container');
add elements to object properties

2020-10-21 11:38 UTC, so2niko commented on app/components/car-details/view-car-details.js
> +                  <button class="third-color" style="background:${color[2]};"></button>
add dynamic render of colors

2020-10-21 11:38 UTC, so2niko commented on app/components/car-details/view-car-details.js
> +                    <option>${transmission[1]}</option>
add dynamic render of transmissions

2020-10-21 11:38 UTC, so2niko commented on app/components/car-details/view-car-details.js
> +  getColor = (event) => {
move to controller and save color in model, not view

2020-10-23 11:58 UTC, so2niko requested changes

2020-10-23 11:58 UTC, so2niko commented on app/components/car-details/model-car-details.js
>    car = {};
delete

2020-10-23 11:58 UTC, so2niko commented on app/components/car-details/controller-car-details.js
> +    this.model.car = car;
delete line

2020-10-26 05:23 UTC, merged