MVC-form
so2niko/Dp-193_proj1 pull request #95
Opened 2020-10-21 11:48 UTC by MarinaPasternak

2020-10-21 12:11 UTC, Anastasiia0999 commented on app/components/acceptForm/form-controller.js
> +    //use git pull to use events for publisherEvents
delete comments

2020-10-21 12:13 UTC, archontis-cpu requested changes
too much eslint errors

2020-10-21 13:32 UTC, rearchontis commented on app/components/acceptForm/form-model.js
> +      car,
Car is undefined, you possibly should use `getCardData` method

2020-10-21 13:32 UTC, rearchontis commented on app/components/acceptForm/form-model.js
> +      customer,
Customer is also undefined, you should use `getFormData`

2020-10-21 13:32 UTC, rearchontis commented on app/components/acceptForm/form-model.js
> +
Should `email` field be here?

2020-10-21 18:16 UTC, PavelKundenko requested changes

2020-10-21 18:16 UTC, PavelKundenko commented on app/components/acceptForm/form-model.js
> +    const url = "https://kolimaga.herokuapp.com/";
Use single quotes, please

2020-10-21 18:16 UTC, PavelKundenko commented on app/components/acceptForm/form-style.scss
> +input[type="text"]{
Better create class for input, using `input[type="text"]` you might overwrite input style in other components

2020-10-21 18:16 UTC, PavelKundenko commented on app/components/acceptForm/form-view.js
> +      let container = document.querySelector('.accept-inform');
"container" variable wouldn't be overwritten, so you can use const.

2020-10-21 18:16 UTC, PavelKundenko commented on app/components/acceptForm/form-view.js
> +        if (key != "photoUrl" && key != "id") {
Single quotes and !== instead of !=

2020-10-21 18:16 UTC, PavelKundenko commented on app/components/acceptForm/form-view.js
> +     this.addDetails = (cardData) => {
Why do you declare a method inside another method? Better move it to class

2020-10-21 18:16 UTC, PavelKundenko commented on app/components/acceptForm/form-view.js
> +        const carDetailsList = this.addDetails(cardData);
Unused constant

2020-10-21 18:16 UTC, PavelKundenko commented on app/components/acceptForm/form-view.js
> +    this.handleSubmitForm = handleSubmitForm
Add semicolon, please

2020-10-21 18:16 UTC, PavelKundenko commented on app/components/acceptForm/form-view.js
> +      for (let key in cardData) {
Use const instead of let

2020-10-22 11:09 UTC, archontis-cpu requested changes
Too much eslint error.
Webpack server cannot start due to errors.

2020-10-22 11:12 UTC, MozdolevskyiMaksym requested changes
add this.events

2020-10-22 11:12 UTC, MozdolevskyiMaksym commented on app/components/acceptForm/form-controller.js
> +    this.subscribe('ADD_ORDER', this.handleAccept)
```
 this.events = events;
this.subscribe('ADD_ORDER', this.handleAccept)
```

2020-10-22 11:19 UTC, MozdolevskyiMaksym commented on app/components/acceptForm/form-controller.js
> +    //this.notify(this.events.SEND_MASSAGE, { fullName, telephone } );
Delete comments

2020-10-22 11:29 UTC, Anastasiia0999 commented on app/components/acceptForm/form-model.js
> +    const response = await fetch('http://www.json-generator.com/api/json/get/ctRVcUtcfC?indent=2');
use property for url

2020-10-22 11:29 UTC, Anastasiia0999 commented on app/components/acceptForm/form-view.js
> +      for (let key in cardData) {
use separate function

2020-10-22 11:29 UTC, Anastasiia0999 commented on app/components/acceptForm/form-controller.js
> +    }
add ; after arrow func + delete 30 line

2020-10-22 11:29 UTC, Anastasiia0999 commented on app/components/acceptForm/form-model.js
> +  }
add ; here after arrow func

2020-10-22 11:35 UTC, MozdolevskyiMaksym commented on app/components/acceptForm/form-model.js
> +    const data = await response.json();
why do you use fetch? You will get the car from Ivan`s component

2020-10-22 11:38 UTC, archontis-cpu commented on app/components/acceptForm/form-view.js
> +      for (const key in cardData) {
Please, don't use `for...in` method without necessary due to running through prototype, use arrays' methods and `Object.entries()`, `Object.keys()`, `Object.values()` instead, e.g. like in the [formatObjectToHTML method](https://github.com/so2niko/Dp-193_proj1/blob/dev/bot/helpers.js)

2020-10-22 19:08 UTC, PavelKundenko approved these changes

2020-10-22 19:25 UTC, MozdolevskyiMaksym approved these changes

2020-10-22 21:30 UTC, archontis-cpu requested changes

2020-10-22 21:30 UTC, archontis-cpu commented on app/main.js
> +import { FormController } from './components/acceptForm/form-controller.js';
Change the path to `'./components/accept-form/form-controller.js'`

2020-10-22 21:38 UTC, MarinaPasternak commented on app/main.js
> +import { FormController } from './components/acceptForm/form-controller.js';
done

2020-10-23 09:56 UTC, archontis-cpu approved these changes

2020-10-23 10:01 UTC, Anastasiia0999 approved these changes

2020-10-23 10:05 UTC, merged